#!/bin/sh

# PROVIDE: rubicure_puma
# REQUIRE: LOGIN

# Add the following line to /etc/rc.conf to enable `rubicure':
#
#rubicure_enable="YES"

. /etc/rc.subr

name="rubicure_puma"
rcvar="rubicure_enable"

load_rc_config "$name"
: ${rubicure_enable="NO"}
: ${rubicure_path=""}
: ${rubicure_user=""}

export PATH=${PATH}:/usr/local/bin:/usr/local/sbin
export LANG=ja_JP.UTF-8
export LC_ALL=ja_JP.UTF-8

start_cmd=${name}_start
stop_cmd=${name}_stop

rubicure_puma_start() {
  cd $rubicure_path
  sudo -u $rubicure_user /usr/sbin/daemon \
    /usr/local/bin/bash -lc "cd ${rubicure_path} && RACK_ENV=production bundle exec bin/puma_daemon.rb start"
}

rubicure_puma_stop() {
  cd $rubicure_path
  sudo -u $rubicure_user /usr/local/bin/bash -lc 'bundle exec bin/puma_daemon.rb stop' 2>/dev/null
  pkill -9 -u $rubicure_user -f 'rubicure.*puma_daemon.rb' 2>/dev/null
  sleep 2
}

run_rc_command "$1"
