package:
  authors:
    - Tatsuya Koishi
  description: プリキュア淑女録スプレッドシートにアクセスするためのAPI。
  email:
    - tkoishi@b-shock.co.jp
  license: MIT
  url: https://github.com/pooza/cure-api
  version: 3.0.0
gas:
  girls:
    url: https://script.google.com/macros/s/AKfycbyz2apomjlyawkhLI-XvZveeEPVvLXmGzshHiE9mfsZT8DOOKAwKRQ_CxzfBiv7Qki33A/exec
  series:
    url: https://script.google.com/macros/s/AKfycbxdqh2CNk71V4-5vsiQ0ruEzF9Eu79pzDFyJiQa_GjgSYk9yCTrSo2lGi0wkiGsX_fU/exec
http:
  retry:
    limit: 3
    seconds: 1
  timeout:
    seconds: 30
puma:
  port: 3009
  workers: 0
  threads: 1
tools:
  - girls
  - series
  - cast
  - livecure
  - help
