package:
  authors:
    - Tatsuya Koishi
  description: モロヘイヤにrubicureにアクセスするためのAPIを提供。
  email:
    - tkoishi@b-shock.co.jp
  license: MIT
  url: https://github.com/pooza/mulukhiya-rubicure
  version: 1.2.0
gas:
  url: https://script.google.com/macros/s/YOUR_DEPLOYMENT_ID/exec
tools:
  - girls
  - series
  - cast
  - livecure
  - help
