package:
  authors:
    - Tatsuya Koishi
  description: モロヘイヤにrubicureにアクセスするためのAPIを提供。
  email:
    - tkoishi@b-shock.co.jp
  license: MIT
  url: https://github.com/pooza/mulukhiya-rubicure
  version: 1.2.0
gas:
  girls:
    url: https://script.google.com/macros/s/AKfycbzmH0v7LRMrgf9u4hqpRHYwOtnc_o1zhVRRpXXWpAsfk-CQcT3Hf8L5iwhTDz42UEnWdQ/exec
  series:
    url: https://script.google.com/macros/s/AKfycbxdqh2CNk71V4-5vsiQ0ruEzF9Eu79pzDFyJiQa_GjgSYk9yCTrSo2lGi0wkiGsX_fU/exec
tools:
  - girls
  - series
  - cast
  - livecure
  - help
