package:
  authors:
    - Tatsuya Koishi
  description: モロヘイヤにrubicureにアクセスするためのAPIを提供。
  email:
    - tkoishi@b-shock.co.jp
  license: MIT
  url: https://github.com/pooza/mulukhiya-rubicure
  version: 1.0.11
tools:
  - girls
  - series
  - cast
  - livecure
  - help
